services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    healthcheck: 
      test: ["CMD", 'mysqladmin', 'ping', '-h', '127.0.0.1', '--silent' ]
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
  backend:
    build: .
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
    environment: 
      PORT: 5000
      MYSQL_HOST: db
    volumes:
      - ./data:/usr/app/public
volumes:
  font-site:
    driver: local
